
#define PASSYARDS 		0
#define COMPLETIONS		1
#define PASSATTEMPTS		2
#define PERCENTAGE		3 
#define PASSINGTOUCHDOWNS	4
#define PASSINGINTERCEPTIONS	5
#define SACKED			6
#define RATING			7


#define RUSHYARDS		8
#define RUSHATTEMPTS 		9
#define RUSHAVERAGE		10
#define RUSHYARDSPERGAME	11
#define RUSHTOUCHDOWNS		12
#define RUSHLONG			13
#define FUMBLES			14


#define RECEPTIONS		15
#define RECEIVINGYARDS		16
#define RECEIVNGTOUCHDOWNS	17
#define RECEVINGYARDSPERGAME	18


#define TACKLES			19
#define SACKS			20
#define SAFETY			21
#define PASSDEFLECTS		22
#define INTERCEPTIONS		23
#define DEFENSIVETOUCHDOWNS	24
#define FOURCEDFUMBLES		25
#define FUMBLERECOVERIES	26

#define KICKRETURNS		27
#define KICKRETURNYARDS		28
#define KICKRETURNAVERAGE	29

#define PUNTRETURNS		30
#define PUNTRETURNYARDS		31
#define PUNTRETURNAVERAGE	32

#define NUM_STATS		32


